- name: add apache iptable rule
  command: /sbin/iptables -I INPUT 1 -p tcp --dport http -j ACCEPT -m comment --comment "Apache" 
  notify:
    - restart iptables
  
- name: install Apache
  yum: name={{ item }} state=present
  with_items:
    - httpd

- name: restart Apache
  service: name=httpd state=restarted enabled=yes
