- name: install Apache
  yum: name={{ item }} state=present
  with_items:
    - httpd
  notify: restart_apache
  
- name: Apache | add apache iptable rule
  command: /sbin/iptables -I INPUT 1 -p tcp --dport http -j ACCEPT -m comment --comment "Apache" 
  notify: restart_iptables