- name: install epel repo
  yum: name={{ item }} state=latest
  with_items:
      - epel-release

- name: install packages
  yum: name={{ item }} state=latest
  with_items:
      - phpmyadmin

- name: copy config file
  template: src=phpMyAdmin.conf.j2 dest=/etc/httpd/conf.d/phpMyAdmin.conf owner=root mode=0644
  notify:
    - restart_apache