- name: install MySQL
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - mysql
    - mysql-server
    - MySQL-python
    
- name: open mysql port
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 3306 -j ACCEPT -m comment --comment "MySQL" 
  notify: restart_iptables
  
- name: edit mysql config
  lineinfile: dest=/{{ mysql_config_path }} line="{{ item }}"
  with_items:
    - "port = {{ mysql_port }}"
    - "bind-address = {{ mysql_bind_address }}"

- name: restart mysql
  service: name=mysqld state=restarted enabled=yes

- name: Change root user password on first run
  mysql_user: login_user=root
              login_password=''
              name=root
              password={{ mysql_root_password }}
              priv=*.*:ALL,GRANT
              host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost